#
# $Log$
# Revision 1.1  2000/11/17 13:26:53  nmw
# Initial revision
#
#

#######################################################################################
#
# General Setup:
#
SAC2CFLAGS = -O3 -v1 -genlib c -noLIR -maxlur 3
#SAC2CFLAGS += -mt
#SAC2CFLAGS += -noopt

#
# Setup for Makefile.standard:
#
# EXCLUDE_FILES               =
# TARGETDIR                   = .
LIBTARGETDIR                = ../lib
# LIBSRCDIR                   = .
# SUBDIRS                     =
# MAKE_NON_LOCAL_DEPENDENCIES = yes
 
#
# Setup for Makefile.check:
#
# CHECKDIR = .checkdir
# RT_FLAGS =
#
#######################################################################################

include $(SACBASE)/stdlib/Makefiles/Makefile_template.prg


