#######################################################################################
#
# General Setup:
#
SAC2CFLAGS = -O3 -v1 -noLIR
 
#
# Setup for Makefile.standard:
#
# TARGETDIR                   = .
# LIBTARGETDIR                = .
# LIBSRCDIR                   = .
# SUBDIRS                     =
# MAKE_NON_LOCAL_DEPENDENCIES =
 
#
# Setup for Makefile.check:
#
# CHECKDIR = .checkdir
# RT_FLAGS =
#
#######################################################################################

include $(SACBASE)/stdlib/Makefiles/Makefile_template.prg




